### ISSUE TITLE
problem: applications disappeared after logged out 

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/emurpas#184]
This only happens to Applicant account 

All in progress application were gone after the applicant logged out 

Entries for example: 

<img width="1274" alt="1119-application-gone" src="https://user-images.githubusercontent.com/44600923/48697677-1e85e480-ec20-11e8-84e1-f4d2b8413da2.png">

**Comment by higunjan** [comment]
@emurgobot claim

**Comment by higunjan** [comment]
After so much debugging I found that `elo cron` running every 10 minute for update `eloRanking`. Previously which `.update` query fire then every 10 second it delete record of participant How I don't know exactly. 

Solution: Used `upsert` instead of `update`.  

Using `upsert` it solved but I think this is not proper way to do it. @MadanBhandari & @anbud Please check and can you elaborate issue

@emurgobot done

**Comment by higunjan** [comment]
@gazhayes Please reopen these issue, solution might affect other functionality.
@emurgobot claim

**Comment by higunjan** [comment]
@emurgobot done
